<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Krishavs-MacBook-Air.local" failures="2" tests="4" name="com.hybridframework.testcases.login.LoginTest" time="13.724" errors="0" timestamp="2025-05-07T02:55:18 IST" skipped="0">
  <testcase classname="com.hybridframework.testcases.login.LoginTest" name="verifyLoginWithValidCredential" time="2.964">
    <failure message="Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:16)
at com.hybridframework.testcases.login.LoginTest.verifyLoginWithValidCredential(LoginTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: Matched:Test Passes expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:14)
... 27 more
]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidCredential -->
  <testcase classname="com.hybridframework.testcases.login.LoginTest" name="verifyLoginWithValidCredential" time="3.759"/>
  <testcase classname="com.hybridframework.testcases.login.LoginTest" name="verifyLoginWithValidCredential" time="4.409">
    <failure message="Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Matched:Test Passes | Expected: Warning: No match for E-Mail Address and/or Password., but got: Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:16)
at com.hybridframework.testcases.login.LoginTest.verifyLoginWithValidCredential(LoginTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.AssertionError: Matched:Test Passes expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.hybridframework.utils.AssertionUtil.hardAssertEquals(AssertionUtil.java:14)
... 27 more
]]>
    </failure>
  </testcase> <!-- verifyLoginWithValidCredential -->
  <testcase classname="com.hybridframework.testcases.login.LoginTest" name="verifyLoginWithInvalidCredential" time="2.592"/>
</testsuite> <!-- com.hybridframework.testcases.login.LoginTest -->
